### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by enesutku07**
android-ramdisk.img not found error fix.

### CODE REVIEW

**Comment by Herrie82** [comment]
@enesutku07 Sorry for the delay, somehow missed the notification for this PR. After fixing this, how far do you get in terms of booting?

**Comment by enesutku07** [comment]
unfortunately, it still doesn't create the file. I'm looking for his solution.

**Comment by enesutku07** [comment]
edit makefile. add patch-2

**Comment by Herrie82** [comment]
@enesutku07  I don't see the 2nd patch?

**Comment by enesutku07** [comment]
https://github.com/enesutku07/android_build/tree/patch-2?files=1

Android için Outlook<https://aka.ms/ghei36>'u edinin

________________________________

**Comment by Herrie82** [comment]
@enesutku07 I'm not trying to pick this up again at my end. I've applied a commit that should hopefully fix this. Based on something similar for 5.1 and 7.1: https://github.com/Herrie82/android_build/commit/a0def43ef045b030b64722ff653aeafd1b48cb43

**Comment by enesutku07** [comment]
Please telegram adress

Android için Outlook<https://aka.ms/ghei36>'u edinin

________________________________

**Comment by enesutku07** [comment]
I hope I don't get it wrong. but I want your work to be beautiful.

**Comment by Herrie82** [comment]
@enesutku07 I can now build 8.1 and get it to boot into a rootfs as well. Just now having issues with init etc. But Ramdisk issue is sorted at least.

**Comment by Herrie82** [comment]
Solved with https://github.com/Herrie82/android_build/commit/11fd95fe9d69042e5891491f8f26ffa412e7077b

Tested with Motorola Cedric and LG/Google Hammerhead

**Pull request closed without merging**
